### ISSUE TITLE
Cython directive 'language_level'

### ISSUE THREAD

**Issue by varalgit** [cjrh/easycython#10]
Very handy tool, this, works well! The only issue I can find is this: If you use the tool, you get this warning:

> FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2).

Is there a way to set the language_level to 3 to make sure Cython uses the correct version of Python and get rid of this warning?

**Comment by bhimesuber** [comment]
You need to specify this in you `.pyx` file by adding
`# cython: language_level=3` toward the top of the file

**Comment by varalgit** [comment]
Yes, that indeed does the trick, thanks!
